name: cptox21_si_testtest
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0=py_2
  - matplotlib=3.3.3=py38h578d9bd_0
  - pandas=1.1.4=py38h0ef3d22_0
  - pip=20.3=pyhd8ed1ab_0
  - scikit-learn=0.23.2=py38h5d63f67_3
  - pip:
    - https://github.com/morgeral/nonconformist/archive/master.zip
